export const dependencyVersions = {
  eslint: '~9.22.0',
  prettier: '~3.5.3',
  husky: '~9.1.7',
  'lint-staged': '~15.4.3',
  '@commitlint/cli': '~19.8.0',
  '@commitlint/config-conventional': '~19.8.0',
  '@typescript-eslint/parser': '~8.26.0',
  '@typescript-eslint/eslint-plugin': '~8.26.0',
  'eslint-config-prettier': '~10.1.1',
  '@vcian/eslint-config-react': '~1.0.0',
  '@vcian/eslint-config-node': '~1.0.0',
  '@vcian/eslint-config-angular': '~1.0.0',
  '@vcian/prettier-config': '~1.0.0',
  '@vcian/commitlint-config': '~1.0.0',
  'eslint-plugin-react-hooks': '~5.2.0',
  'eslint-plugin-jsx-a11y': '~6.10.2',
  'eslint-plugin-import': '~2.31.0',
  'eslint-plugin-unused-imports': '~4.1.4',
  'eslint-plugin-n': '~17.16.2',
  'eslint-plugin-security': '~3.0.1',
  '@angular-eslint/builder': '~19.2.0',
  '@angular-eslint/eslint-plugin': '~19.2.0',
  '@angular-eslint/eslint-plugin-template': '~19.2.0',
  '@angular-eslint/template-parser': '~19.2.0',
  '@darraghor/eslint-plugin-nestjs-typed': '~5.0.2',
} as const;

export type DependencyName = keyof typeof dependencyVersions;
